import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'girish',
      email: 'girish@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
  ],
  products: [
    {
      //_id:'1',
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 540,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id:'2',
      name: 'Adidas Fit shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 620,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.3,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id:'3',
      name: 'Nike slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 550,
      countInStock: 20,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      //_id:'4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 589,
      countInStock: 25,
      brand: 'Adidas',
      rating: 4.4,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id:'5',
      name: 'Adjustable Dumbells',
      slug: 'adjustable-dumbells',
      category: 'Fitness',
      image: '/images/p5.webp',
      price: 16899,
      countInStock: 20,
      brand: 'FlexiBell',
      rating: 4.7,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      //_id:'6',
      name: 'Adjustable Kettlebell',
      slug: 'adjustable-kettlebell',
      category: 'Fitness',
      image: 'https://m.media-amazon.com/images/I/61EU055CyzL._SX425_.jpg',
      price: 7899,
      countInStock: 28,
      brand: 'FlexiBell',
      rating: 4.2,
      numReviews: 16,
      description: 'high quality product',
    },
    {
      //_id:'7',
      name: 'Ear Pods',
      slug: 'ear-pods',
      category: 'Electronis',
      image:
        'https://assets.ajio.com/medias/sys_master/root/20220322/PZlJ/6238de7baeb26921afe97655/-473Wx593H-4925790880-multi-MODEL.jpg',
      price: 2499,
      countInStock: 15,
      brand: 'Crossbeats',
      rating: 4.1,
      numReviews: 26,
      description: 'high quality product',
    },

    {
      //_id:'8',
      name: 'EDITH Eye Glasses',
      slug: 'EDITH-eye-glasses',
      category: 'EyeWear',
      image: 'https://m.media-amazon.com/images/I/61vxbCN5UgL.UL1500.jpg',
      price: 1799,
      countInStock: 27,
      brand: 'LensFitz',
      rating: 4.0,
      numReviews: 16,
      description: 'high quality product',
    },
    {
      //_id:'9',
      name: 'MRF Cricket Bat',
      slug: 'MRF-LEGEND',
      category: 'Sports',
      image: 'https://lsmedia.linker-cdn.net/62267/2022/7377821.jpeg?d=400x400',
      price: 15899,
      countInStock: 15,
      brand: 'MRF',
      rating: 4.7,
      numReviews: 56,
      description: 'high quality product',
    },
    {
      //_id:'10',
      name: 'Hemcut Hoodie',
      slug: 'hemcut-hoodie',
      category: 'GymWear',
      image:
        'https://cdn.shopify.com/s/files/1/0534/3094/3907/products/4@2x.png?v=1635014794',
      price: 1589,
      countInStock: 22,
      brand: 'MuscleWolves',
      rating: 3.8,
      numReviews: 112,
      description: 'high quality product',
    },
  ],
};
export default data;
