const data = {
  products: [
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 540,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 620,
      countInStock: 30,
      brand: 'Adidas',
      rating: 4.3,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 550,
      countInStock: 20,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 589,
      countInStock: 25,
      brand: 'Adidas',
      rating: 4.4,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
